[package]
name = "factorio-printer"
version = "0.1.0"
authors = ["vixfwis <vixfwis at github.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
image = "0.23"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
flate2 = "1.0"
base64 = "0.13"